//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NetMsg.rc
//
#define ID_SEND                         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NETMSG_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDC_EDITMSG                     1000
#define IDC_INFO                        1001
#define IDC_EDITHOST                    1004
#define IDC_TOALL                       1005
#define IDC_CLRAFTRSEND                 1006
#define IDC_LOOP                        1007
#define IDC_REPEATCYCLE                 1008
#define IDC_STOPLOOP                    1009
#define IDC_RENAMEWIN                   1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
